### ISSUE TITLE
Prompt Not working as expected

### ISSUE THREAD

**Issue by Oldault** [Oldault/minishell42#12]
## Prompt Not working as expected
When you enter minishell you see something ressembling :
```user@minishell: ~directory```
Which is missing a key element to simulate bash, the "/" sign after the tilde ("~"). So the actual prompt should look something like this:
```user@minishell: ~/directory```

**Comment by Oldault** [comment]
command to set path to home is : `cd ~`

**Comment by alessiobenincasa** [comment]
I fixed the problem in the prompt using the memmove function
